name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build ping_pong
        run: pio run
        
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/heltec_wifi_lora_32_V3/firmware.bin
